name: Release - Platform

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release Version (could match the Dirigible version for more clearance)
        required: false
      snapshot-version:
        description: Snapshot Version
        required: true
        default: 13.0.0-SNAPSHOT

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract dirigible.version from pom.xml
        id: get-version
        run: echo "version=$(mvn help:evaluate -Dexpression=dirigible.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"

  release:
    needs: extract-version
    uses: codbex/codbex-infra/.github/workflows/platform-release.yaml@main
    with:
      platform-name: codbex-platform-parent
      maven-release: true
      code-scans: false
      docker-release: false
      release-version: ${{ inputs.release-version != '' && inputs.release-version || needs.extract-version.outputs.release-version }}
      snapshot-version: ${{ inputs.snapshot-version }}
      release-content: |
        ## codbex-platform-parent - ${{ inputs.release-version != '' && inputs.release-version || needs.extract-version.outputs.release-version }}

        codbex platform parent project.

        ```xml
        <dependency>
            <groupId>com.codbex.platform</groupId>
            <artifactId>codbex-platform-parent</artifactId>
            <version>${{ inputs.release-version != '' && inputs.release-version || needs.extract-version.outputs.release-version }}</version>
        </dependency>
        ```

    secrets: inherit
